### ISSUE TITLE
[Feature Request] receive format for udp packet version 3

### ISSUE THREAD

**Issue by qlin960618** [SmartArmStack/smart_arm_master_windows#1]
Hi @mmmarinho,

Thanks again for the continous support in everything.
Regarding the example code provided, I am wondering is there a reason that the return information from follower to leader udp format is not provided?

**Comment by mmmarinho** [comment]
@qlin960618 Hmn... everything indicates this is the first time anyone bothered enough to open an issue about it so, maybe... the lack of demand?

Another issue might be that, with multiple remotes, the force feedback becomes trickier and I don't remember addressing this, because I never had to.

**Comment by qlin960618** [comment]
@mmmarinho 
I see, so I guess that reciever doesn't have to send back any information for the master side to work? In that case I guess this is not a priority then...
Although the current sas_operator_side_receiver I think I am able to send back with some force feedback? maybe this is just legacy code thats not removed?

**Comment by mmmarinho** [comment]
@qlin960618 As far as I remember, it is possible and is implemented in the code. 
I just didn't write the protocol down because nobody asked?
